version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data/

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db

volumes:
  dbdata: null
