"""empty message

Revision ID: e5e9ee915819
Revises: 
Create Date: 2023-10-15 15:03:49.898482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e9ee915819'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('title', sa.String(), nullable=False),
                sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
                sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('answer', sa.String(), nullable=False),
                sa.Column('question', sa.String(), nullable=False),
                sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
                sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                sa.Column('category_id', sa.Integer(), nullable=False),
                sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    # ### end Alembic commands ###
